name: First Workflow
on: [push]
jobs:
    run-shell-comands:
        runs-on: ubuntu-latest
        steps:
            - name: "echo as String"
              run: echo "Hello"
            - name: Multiline command
              run: |
               node -v
               npm -v
    parallel-job-macos:
        runs-on: macos-latest
        steps:
            - name: view sw version
              run: sw_version
    dependent-job:
        runs-on: windows-latest
        needs: run-shell-comands
        steps:
            - name: echo a string
              run: Write-Output "Windows String"   
            - name : Error Step
              run: doesnotexits