name: Node.js CI

on:
  workflow_dispatch:
    inputs:
      playwright-version:
        description: 'Select Playwright Docker image version'
        required: true
        default: '1.56.0'
        type: choice
        options:
          - '1.56.0'
          - '1.55.0'
          - '1.54.2'
          - '1.53.0'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-24.04

    container:
      image: mcr.microsoft.com/playwright:v${{ inputs.playwright-version }}-jammy

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Check Node and npm versions
        run: |
          node --version
          npm --version
          which node

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Run tests
        run: npm test
